### ISSUE TITLE
Negative methane concentration in GEOS-Chem crashes IMI

### ISSUE THREAD

**Issue by djvaron** [geoschem/integrated_methane_inversion#118]
GEOS-Chem crashes when negative methane concentrations are encountered. This crashes the IMI. 

It's a rare occurrence, but it can happen, for example, if a buffer element receives a strongly negative posterior scale factor leading to strong negative emissions and thus negative concentrations in the lowest model layer.

A fix could be to update GEOS-Chem to replace negative concentrations with a small value (e.g., `1e-20`) and issue a warning.

**Comment by msulprizio** [comment]
@djvaron Is this issue still occurring? If so, do you recall where in GEOS-Chem it's happening? I can add a fix in 14.3.1.

**Comment by djvaron** [comment]
I haven't encountered this problem since I first reported it. My solution was to reset the prior estimates for the buffer elements after each weekly inversion in the Kalman filter framework (as we had done previously).

Have there been any updates to handle negative methane concentrations in GC or do they still crash the model? Crashing seems reasonable to me since encountering negative concentrations due to a very strong buffer element scale factor would suggest the boundary conditions are deficient.

**Comment by msulprizio** [comment]
We did not end up making a change to allow for negative methane concentrations in GEOS-Chem, so the model should still crash if negative values are encountered. I will close out this issue for now since we want to keep this behavior.
