### ISSUE TITLE
[FEATURE REQUEST] Clean-up options

### ISSUE THREAD

**Issue by djvaron** [geoschem/integrated_methane_inversion#129]
### Name and Institution (Required)

Name: Daniel Varon
Institution: Harvard University

### New IMI feature or discussion

The IMI currently produces much more output data than needs to be archived in practice. We should introduce options to clean up inversion directories after running the IMI.

A starting point would be an option to automatically remove the `data_sensitivities` folder, which is used to generate the Jacobian sensitivity files, is generally not needed after that has been done, and tends to be very large.

**Comment by djvaron** [comment]
We may also want to use some of the `encoding` options availabe with [`to_netcdf()`](https://docs.xarray.dev/en/stable/generated/xarray.Dataset.to_netcdf.html) in `xarray`.

**Comment by laestrada** [comment]
> We may also want to use some of the `encoding` options availabe with [`to_netcdf()`](https://docs.xarray.dev/en/stable/generated/xarray.Dataset.to_netcdf.html) in `xarray`.
> 
> EDIT: James East recommends something like `ds.to_netcdf('file.nc', encoding={v: {'zlib':True,'complevel':1} for v in ds.data_vars}})`

Using compression is addressed by #143

**Comment by msulprizio** [comment]
This is resolved by https://github.com/geoschem/integrated_methane_inversion/pull/184
