### ISSUE TITLE
Statevector defined domain is truncated by buffer zone in nested regions.

### ISSUE THREAD

**Issue by laestrada** [geoschem/integrated_methane_inversion#134]
### Name and Institution (Required)

Name: Lucas Estrada
Institution: Harvard ACMG

### Name and Institution (Required)

Name: Lucas Estrada
Institution: Harvard ACMG

### New IMI feature or discussion
Currently GEOS-Chem defines the statevector max/min lat and lon grid centers as the domain edges. But because of the nested domain [buffer zone](https://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_nested_grid_simulations), 3-4 grid cells get chopped off on each side of the domain. This can be misleading for users because the outputted domain is different from the inputted lats/lons.

To fix this issue we should add a function that takes the user-defined statevector and pads it with 3 gridcells (labeled with 0 to prevent additional jacobian simulations). This function should also check whether the buffer-zone gridcells have already been added to the domain to prevent unexpected bloat of the domain when repeatedly running the IMI.

This should not be an issue for most users as long as they are using sufficient large buffer elements surrounding their domain of interest.

**Comment by msulprizio** [comment]
@laestrada Is this still an issue?

**Comment by laestrada** [comment]
@msulprizio I believe this is still an issue
