### ISSUE TITLE
Update IMI Boundary Conditions to use 2x2.5 degree simulation

### ISSUE THREAD

**Issue by laestrada** [geoschem/integrated_methane_inversion#146]
### New IMI feature or discussion

Name: Lucas Estrada
Institution: Harvard ACMG

### Description of your issue or question
Our boundary condition scripts currently use a 4x5 degree resolution simulation, but work by Todd and others suggests that using 2x2.5 degree simulations vastly improves transport and vertical distribution in the troposphere and stratosphere when compared to observations.

We should update the BCs to use the 2x2.5 degree simulation when we update to version 2.0/

**Comment by nicholasbalasus** [comment]
Closed by #156
