### ISSUE TITLE
Enforce (and download) GCClassic version for the IMI

### ISSUE THREAD

**Issue by laestrada** [geoschem/integrated_methane_inversion#147]
### Name and Institution (Required)

Name: Lucas Estrada
Institution: Harvard ACMG

### New IMI feature or discussion
WHen downloading the IMI for local cluster use, the user separately need to git clone GCClassic using the correct version that the IMI expects. We should update the IMI to either have GCClassic as a submodule in the repository (using the correct version) or have the IMI download and install GCClassic at runtime, similar to how @nicholasbalasus set up the BC scripts. If the latter, it should check if GCClassic is already installed, and, if so, skip the download.

**Comment by msulprizio** [comment]
This is now done in #156. I will close out this issue.
