### ISSUE TITLE
Virtual Environment Configuration

### ISSUE THREAD

**Issue by DajaE1** [geoschem/integrated_methane_inversion#149]
### Name and Institution (Required)

Name: Daja Elum
Institution: Howard University

### Description of your issue or question

Hello, I am trying to run a preview run on imi via AWS and have experienced issues with storage. My instance displays I have storage left however, the imi states that there are no usable temp directories and whenever I tried to run run_imi.sh, a 'Batch job submission failed: I/O error writing script/environment to file' error shows. 

I'm using the c5.9xlarge instance.

**Comment by laestrada** [comment]
Hi Daja,

This sounds like an instance misconfiguration issue. I would recommend terminating your current instance and creating a new one. Perhaps take screenshots of any storage configuration so you can send it in for additional debugging help.

--
Lucas
