### ISSUE TITLE
Visualization notebook(s) are hard-coded to assume running on AWS 

### ISSUE THREAD

**Issue by djvaron** [geoschem/integrated_methane_inversion#154]
### Name and Institution (Required)

Name: Daniel Varon
Institution: Harvard

### Description of your issue or question

I noticed this issue while testing the `dev-2.0` branch with the new feature to automatically run the visualization notebook and save output to html. The notebook looks for `config.yml` at `/home/ubuntu/integrated_methane_inversion/config.yml`, which only works when running the IMI on AWS. 

Could update the notebook(s) on the basis of the `isAWS` config variable or by using relative paths.

**Comment by laestrada** [comment]
Addressed by dev-2.0@3be64d26 and dev-2.0@b9ee8499. Closing.
