### ISSUE TITLE
[FEATURE REQUEST] Improve traceability of shell script variables

### ISSUE THREAD

**Issue by djvaron** [geoschem/integrated_methane_inversion#158]
### Name and Institution (Required)

Name: Daniel Varon
Institution: Harvard University

### New IMI feature or discussion

The componentized IMI lacks traceability of variables in component shell scripts. For example, it's unclear from where the `i` variable is inherited in the `kalman.sh` function `run_period()`.

Suggested fix is to add comment headers to all shell scripts detailing where variables are defined/inherited. For example, `run_inversion.sh` currently includes the following comment where the config file is read in:

```
# Get configuration
#  This defines $StartDate, $EndDate, $nBufferClusters, $RunName, $isAWS
#  It also define $PriorError, $ObsError, $Gamma, $PrecomputedJacobian
```

**Comment by laestrada** [comment]
Closing with #159
