### ISSUE TITLE
Default LevelEdgeDiags collection saves out more variables than are needed

### ISSUE THREAD

**Issue by nicholasbalasus** [geoschem/integrated_methane_inversion#171]
### Name and Institution (Required)

Name: Nick Balasus
Institution: Harvard University

### New IMI feature or discussion

Currently, the IMI archives the LevelEdgeDiags collection hourly which by default includes 7 variables. 6 of these are not used, suggesting the data size for hourly LevelEdgeDiags files can be reduced by ~86% making a simple change in HISTORY.rc with a sed command in the template creation.

```
  LevelEdgeDiags.fields:      'Met_CMFMC                     ',
                              'Met_PEDGE                     ',
                              'Met_PEDGEDRY                  ',
                              'Met_PFICU                     ',
                              'Met_PFILSAN                   ',
                              'Met_PFLCU                     ',
                              'Met_PFLLSAN                   ',
```

to

```
  LevelEdgeDiags.fields:      'Met_PEDGE                     ',
```

This only impacts prior and posterior runs.

**Comment by msulprizio** [comment]
This was addressed by updates in PR https://github.com/geoschem/integrated_methane_inversion/pull/175 and will be included in IMI 2.0 We now only save out a reduced set of hourly pressure fields to daily files for the base run.
