### ISSUE TITLE
Corrupted strings in imi_output.log

### ISSUE THREAD

**Issue by msulprizio** [geoschem/integrated_methane_inversion#187]
### Name and Institution (Required)

Name: Melissa Sulprizio
Institution: Harvard / GCST

### Description of your issue or question

I noticed some of the output in imi_output.log is getting corrupted. This is occurring in at least two places:

(1) When printing output from the IMI preview:

<img width="654" alt="Screenshot 2024-02-09 at 10 15 14 AM" src="https://github.com/geoschem/integrated_methane_inversion/assets/4805437/c49729b7-ab03-4886-8e29-fbfe9a949825">

This appears to be caused by printing `outstring3 = f"k = {np.round(k,5)} kg-1 m2 s"` in imi_preview.py.

(2) When printing out which jacobian simulations have finished:

<img width="998" alt="Screenshot 2024-02-09 at 10 16 32 AM" src="https://github.com/geoschem/integrated_methane_inversion/assets/4805437/21ebce18-7c0f-4b91-a10a-9181575dd42c">

I suspect this one may be because too many jobs are attempting to write to imi_output.log at the same time. Perhaps we can suppress these messages to avoid corrupting the file?

**Comment by nicholasbalasus** [comment]
Hi Melissa - I have experienced this as well. For me, it sometimes shows up as the weird behavior of the error initially printing to the output log like this:
![image](https://github.com/geoschem/integrated_methane_inversion/assets/91984611/3454f423-72e3-4149-b1ff-373a68cc77a1)

And then updating to corrupted characters:
![image](https://github.com/geoschem/integrated_methane_inversion/assets/91984611/cca6d6ca-a089-4f63-83c5-4882b1c486ea)

Maybe related to https://github.com/geoschem/integrated_methane_inversion/issues/136

**Comment by nicholasbalasus** [comment]
Closed by #199
