### ISSUE TITLE
SRON plume data not being fetched for use in state vector aggregation (dev branch)

### ISSUE THREAD

**Issue by eastjames** [geoschem/integrated_methane_inversion#197]
Name: James East
Institution: Harvard ACMG

SRON plume csv files are scraped from the SRON website in these lines:
https://github.com/geoschem/integrated_methane_inversion/blob/ed50db58cf180cbfcfb4b3fae4d994b3b26cfd8d/src/inversion_scripts/point_sources.py#L91C1-L92C1

IMI scrapes csv files from https://earth.sron.nl/wp-content/uploads. However, it looks like the permissions to access "wp-content/uploads" have changed recently. As a result, the files there can't be publicly accessed, and SRON plumes aren't used in state vector aggregation.

**Comment by jdmaasakkers** [comment]
We'll try to come up with a solution on our (SRON) side.

**Comment by jdmaasakkers** [comment]
The information is now available on http://ftp.sron.nl/pub/memo/.

**Comment by jdmaasakkers** [comment]
The plumes can now be found at https://ftp.sron.nl/pub/memo/.

**Comment by eastjames** [comment]
Thank you, Bram!
