### ISSUE TITLE
The preview module did not run.

### ISSUE THREAD

**Issue by whzlatan** [geoschem/integrated_methane_inversion#198]
### Name and Institution (Required)

Name: zlatan
Institution: Leiden University

### Description of your issue or question

Dear IMI team, I am running IMI on AWS and I have found that sometimes the preview does not run (in PD state), and the log file does not show any prompts

![image](https://github.com/geoschem/integrated_methane_inversion/assets/104134846/74298aec-b328-4383-a9d1-23517dbf4591)
![image](https://github.com/geoschem/integrated_methane_inversion/assets/104134846/323e6e90-7e8b-4c11-90df-41da1864e6c6)
[imi_output.log](https://github.com/geoschem/integrated_methane_inversion/files/14813044/imi_output.log)
[config.zip](https://github.com/geoschem/integrated_methane_inversion/files/14813046/config.zip)

**Comment by laestrada** [comment]
Hi @whzlatan,

Based on your config file I suspect that you are requesting more resources than the instance has available. You have 
```
SimulationCPUs: 32
SimulationMemory: 32000
```
Try reducing these values based on your instance type resources. Note: the run_imi.sh job also takes up some resources.

Let us know if this fixes the issue!

**Comment by whzlatan** [comment]
> 嗨，
> 
> 根据您的配置文件，我怀疑您请求的资源多于实例的可用资源。你有
> 
> ```
> SimulationCPUs: 32
> SimulationMemory: 32000
> ```
> 
> 尝试根据您的实例类型资源来减小这些值。注意：run_imi.sh作业也会占用一些资源。
> 
> 如果这解决了问题，请告诉我们！

After changing the number of CPUs to 30, the problem was resolved. Thank you.
