### ISSUE TITLE
Missing CH4 post meter emissions source for GHGI in HEMCO_Config.rc

### ISSUE THREAD

**Issue by nicholasbalasus** [geoschem/integrated_methane_inversion#202]
### Name and Institution (Required)

Name: Nick Balasus
Institution: Harvard

### Description of your issue or question

Flagging the issue in https://github.com/geoschem/geos-chem/issues/2259. I'll add this line with `sed` so we can still use GEOS-Chem 14.3.1 with IMI 2.0.

**Comment by msulprizio** [comment]
Thanks @nicholasbalasus!

**Comment by nicholasbalasus** [comment]
Fixed in 14.4.1 which is now in dev.
