### ISSUE TITLE
IndexError when running IMI preview with custom coordinates

### ISSUE THREAD

**Issue by LuisGrajales** [geoschem/integrated_methane_inversion#203]
### Name and Institution (Required)

Name: Luis Octavio Grajales
Institution: Talanza Energy

### Description of your issue or question
When running IMI the program crashes in the step RUNNING IMI PREVIEW. The log file throws an IndexError in the estimate_averaging_kernel function, more details in the log file below.

When I run the default preview it runs without an issue, only when I change the coordinates I get this error. I've tried with different coordinates, different dates and running it in a new instance but nothing seems to fix it. Also I'm running the script using tmux.

version: latest (1.2.1)
[config.txt](https://github.com/geoschem/integrated_methane_inversion/files/15120336/config.txt)
[log.txt](https://github.com/geoschem/integrated_methane_inversion/files/15120375/log.txt)

tmux window 
![image](https://github.com/geoschem/integrated_methane_inversion/assets/49939259/775fba6a-5d84-4bbf-b15f-192a43a3f527)

**Comment by laestrada** [comment]
Hi Luis,

Based on your config file, it seems that you have entered a region of interest that is too small for the IMI grid. The IMI has a maximum resolution of .25x.3125 degrees (~25x25km). The lat/lon you entered is less than a single grid cell -- you can try expanding your region of interest size and running again.

--
Lucas and the IMI Team

**Comment by LuisGrajales** [comment]
Hi Lucas,

Thanks for the fast response! 

We've tried running it with different coordinates and we're still getting the same error. I'll attach the last run that we tried, it's using coordinates in a similar range as the default preview but it still throws the same error.

Looking at the code a think the issue might be on line 544 `preview_dir = sys.argv[4]` but that's as far as I got, I don't know what argument is being passed down.

Do you have any other ideas as to what might be causing this?

[log.txt](https://github.com/geoschem/integrated_methane_inversion/files/15123302/log.txt)
[config.txt](https://github.com/geoschem/integrated_methane_inversion/files/15123304/config.txt)

We've also tried with these coordinates.
```
LonMin: -99
LonMax: -98
LatMin: 21
LatMax: 22
```
and
```
LonMin: -99
LonMax: -98.5
LatMin: 21
LatMax: 21.5
```

**Comment by laestrada** [comment]
Hi @LuisGrajales,

It appears there is a slight mismatch in the specification of the boundary condition files. To fix this, update `RestartFilePrefix` and `RestartFilePreviewPrefix` to the following in the config.yml file:

```
RestartFilePrefix: "/home/ubuntu/ExtData/BoundaryConditions/v2023-06/GEOSChem.BoundaryConditions."
RestartFilePreviewPrefix: "/home/ubuntu/ExtData/BoundaryConditions/v2023-06/GEOSChem.BoundaryConditions."
```

**Comment by laestrada** [comment]
I have pushed an update in #204. Closing this issue, but feel free to reopen it if you run into additional issues.
