### ISSUE TITLE
Consistent Colors in Sectoral Disaggregation 

### ISSUE THREAD

**Issue by JohnThomasSEAS** [geoschem/integrated_methane_inversion#222]
Would be great to have consistent colors on the sector breakdown for consistent comparison across different runs. Will be especially important in a dashboard environment, I think.

![Screenshot 2024-05-20 at 9 06 27 AM](https://github.com/geoschem/integrated_methane_inversion/assets/162159685/26362847-8891-4399-86d3-28b2dd162d18)

**Comment by laestrada** [comment]
@JohnThomasSEAS 
I think we are going to switch from the pie chart to a bar chart comparison of the different sectors. Something like this:
<img width="389" alt="image" src="https://github.com/geoschem/integrated_methane_inversion/assets/63303345/0eb43002-ff37-433d-b41d-391004f136d0">

**Comment by JohnThomasSEAS** [comment]
Ok, cool. I might play around with different viz strategies for the dashboard. I do kind of like the look of a pie chart over a bar chart, and there are some great pie chart packages for React.
