### ISSUE TITLE
[BUG/ISSUE] Error setting up preview GC simulation

### ISSUE THREAD

**Issue by djvaron** [geoschem/integrated_methane_inversion#27]
The dry run for the 1-day preview simulation throws this error:

`fatal error: An error occurred (404) when calling the HeadObject operation: Key "HEMCO/../BoundaryConditions/GEOSChem.BoundaryConditions.20180401_0000z.nc4" does not exist`

This path would work:

`../../ExtData/HEMCO/../BoundaryConditions/GEOSChem.BoundaryConditions.20180401_0000z.nc4`

Unclear why `../../ExtData` is missing for this file.

All that said, the error seems to be irrelevant -- the needed boundary condition file is present and the simulation runs correctly.

**Comment by laestrada** [comment]
This looks like the format of a failed `aws s3 cp` command. That path does look odd... the boundary conditions should exist at `s3://imi-boundary-conditions/GEOSChem.BoundaryConditions.20180401_0000z.nc4`
