### ISSUE TITLE
IMI Stalling at HEMCO prior emissions simulation

### ISSUE THREAD

**Issue by zelcon01** [geoschem/integrated_methane_inversion#295]
### Name and Institution (Required)

Name: Nicholas Kinsella
Institution: Ulster Univeristy 

### Description of your issue or question
The IMI Preview seems to stall at the stage indicated. I've run it sucessfully before with the permian basin example but now that I've selected my study location (Algeria), it seems to get stuck. 

I'm continuing to let it run on the off chance I'm wrong but it has already been 2 hours for a IMI preview of 1 week that I believe should only take ~15 minutes. 

My IMI_output.log is attached. 
[imi_output.log](https://github.com/user-attachments/files/18065750/imi_output.log)

Any insight would be welcome. Thanks in advance. 
Nick Kinsella

**Comment by laestrada** [comment]
Hi @zelcon01,

It looks like there are some errors occurring when making the state vector file. Are you using a custom shapefile? or just defining the lat/lons? Can you pass along your config.yml file?

**Comment by zelcon01** [comment]
[## IMI configuration file.txt](https://github.com/user-attachments/files/18065991/IMI.configuration.file.txt)

Yes of course. There it is.

Thank you for the fast response!

**Comment by laestrada** [comment]
Hi @zelcon01,

It looks like you need to specify `RegionId: "AF"` instead of `"NA"`

**Comment by zelcon01** [comment]
Okay. Thanks very much. I'll give that a go now.

**Comment by zelcon01** [comment]
Okay. That worked a lot better. One other thing that seems to be incorrect is that my prior emission data looks like this

![preview_prior_emissions (1)](https://github.com/user-attachments/assets/32ab0f14-b189-426e-bda5-0cc4cbcc9b7e)

Any idea why and how I can correct that?

**Comment by laestrada** [comment]
Try removing this from your config file:

```
ForcedNativeResolutionElements:
  - [31.5, -104]
```

**Comment by zelcon01** [comment]
@laestrada that's worked great. Thanks very much!
