### ISSUE TITLE
Adjust recommended vCPU configuration for default user

### ISSUE THREAD

**Issue by BenHmiel** [geoschem/integrated_methane_inversion#41]
Followed [documentation](https://integrated-methane-inversion.readthedocs.io/en/latest/getting-started/quick-start.html#launch-an-instance-with-the-imi) to set up first EC2 instance.  In step 3 for setting up the EC2 instance, documentation suggests **c5.9xlarge** 36 core vCPU instance, however as a new user to AWS there appears to be a limit on 32core vCPUs which results in the following error when attempting to launch the instance:

![image](https://user-images.githubusercontent.com/61123301/161443273-9452fa34-d7a2-4ee5-8496-fecc073088f1.png)

Suggested resolution: Alter documentation to recommend **c5a.8xlarge** 32 core vCPU for first time users to bypass this limitation.

**Comment by laestrada** [comment]
Hi @BenHmiel, 

Thanks for bringing this to our attention. AWS does have a vcpu limit at 32 vcpus for new aws accounts. You can [request a limit increase](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-on-demand-instances.html#vcpu-limits-request-increase) and they are usually quite quick to update it. 

Thanks,
Lucas
