### ISSUE TITLE
Instruct user to setup EC2 "Security Group" for connecting to Jupyter Server 

### ISSUE THREAD

**Issue by BenHmiel** [geoschem/integrated_methane_inversion#42]
Had difficulty connecting to Jupyter Server setup on EC2 in order to run the visualization ipynb file.  

Did some googling and realized that the user needs to setup a security group to allow access to the right ports.

Followed step 2 in guide here:
https://dataschool.com/data-modeling-101/running-jupyter-notebook-on-an-ec2-server/

Would be worthwhile to add to the readthedocs page for assistance to other users.

**Comment by laestrada** [comment]
We have added some additional documentation for [setting up jupyter on EC2](https://imi.readthedocs.io/en/latest/advanced/setting-up-jupyter.html). Closing this issue.
