### ISSUE TITLE
release of AMI ID & Name

### ISSUE THREAD

**Issue by kachiO** [geoschem/integrated_methane_inversion#49]
Hello, 
What's the ETA on the release of the AMI ID & Name for the model?

**Comment by Kieran-Lynn** [comment]
@kachiO what caused you to close this issue? Did you find the id and name?

**Comment by laestrada** [comment]
Hi @Kieran-Lynn, 

Thanks for reaching out and for your interest in the IMI. We are planning to wrap up beta testing over the next 2-3 weeks and release the final AMI along with the accepted journal paper sometime in early June. If you'd like to start using the IMI before we make the official release, feel free to contact me or Daniel Varon via email (lestrada@g.harvard.edu or dvaron@g.harvard.edu) and we can get you set up with the beta version. Additionally, let us know how you plan to use the IMI -- we excited to hear about use cases!

Thanks,
Lucas Estrada
