### ISSUE TITLE
AMI does not exist

### ISSUE THREAD

**Issue by Kieran-Lynn** [geoschem/integrated_methane_inversion#50]
The docs do not actually specify an AMI. This make setting up an EC2 instance way more difficult. 

![image](https://user-images.githubusercontent.com/8461436/169117547-0c0e1a62-9eb9-4b05-aba7-f8e75d38df23.png)

**Comment by laestrada** [comment]
Hi @Kieran-Lynn,

Thanks for reaching out and for your interest in the IMI. We are planning to wrap up beta testing over the next 2-3 weeks and release the final AMI along with the accepted journal paper sometime in early June. If you'd like to start using the IMI before we make the official release, feel free to contact me or Daniel Varon via email ([lestrada@g.harvard.edu](mailto:lestrada@g.harvard.edu) or [dvaron@g.harvard.edu](mailto:dvaron@g.harvard.edu)) and we can get you set up with the beta version. Additionally, let us know how you plan to use the IMI -- we excited to hear about use cases!

Thanks,
Lucas Estrada
