### ISSUE TITLE
[FEATURE REQUEST] Add capability to optimize offshore emissions

### ISSUE THREAD

**Issue by msulprizio** [geoschem/integrated_methane_inversion#52]
The current state vector creation scripts only consider regions over land. Ideally we would also include offshore emissions; however that requires emissions output from a prior simulation (perhaps even just a HEMCO standalone simulation). Hannah Nesser has developed this capability in her work and we may be able to bring that into the IMI as an option.

**Comment by djvaron** [comment]
Adding to this, offshore emissions *can* currently be optimized as part of the region of interest, but only in one of two ways:

1. Reduce the minimum landcover fraction to 0 -- but this will include all ocean cells in the state vector.
2. Manually edit the state vector file after default generation, to include offshore elements in the region of interest

Both of these approaches are unwieldy so we will want to facilitate the process in the near future.

**Comment by msulprizio** [comment]
This has been addressed by https://github.com/geoschem/integrated_methane_inversion/pull/109
