### ISSUE TITLE
[FEATURE REQUEST] Add capability for log normal errors

### ISSUE THREAD

**Issue by msulprizio** [geoschem/integrated_methane_inversion#63]

**Comment by sarahhancock** [comment]
Hi, I was curious what the priority for this feature request is! I am planning on doing this for my inversion and don't want to duplicate any work already being done. Thanks!!

**Comment by msulprizio** [comment]
Hi @sarahhancock. No one has volunteered for this item yet so it would be great if you wanted to do it.

**Comment by msulprizio** [comment]
This has been included in IMI 2.0
