### ISSUE TITLE
[FEATURE REQUEST] State vector clustering options for large inversion domains

### ISSUE THREAD

**Issue by djvaron** [geoschem/integrated_methane_inversion#68]
Inversions for large domains (e.g., CONUS, Russia) would currently be very expensive, with very large state vectors. 

Some possible options to shrink the state vector:
- Smart clustering of grid cells to user-specified number of state vector elements
- Gaussian mixture model (GMM) with radial basis functions

**Comment by msulprizio** [comment]
The IMI now includes a clustering option
