### ISSUE TITLE
[FEATURE REQUEST] Incorporate information on point sources

### ISSUE THREAD

**Issue by djvaron** [geoschem/integrated_methane_inversion#71]
Include information on known point sources in region of interest where available.

Possibilities:
- Display known point sources as part of the preview
- Increase prior error for grid cells with known point sources
- Increase prior estimate for grid cells with known point sources

**Comment by msulprizio** [comment]
This has been addressed by https://github.com/geoschem/integrated_methane_inversion/pull/219 and will be included in IMI 2.0
