### ISSUE TITLE
[FEATURE REQUEST] Add CPU/memory options to local cluster configuration

### ISSUE THREAD

**Issue by djvaron** [geoschem/integrated_methane_inversion#97]
New config options for running the IMI locally, to set the CPU/memory resources desired for different GEOS-Chem runs, would be helpful.

Currently all runs are set up identically from the `ch4_run.template` file. It would be nice to instead have config options like this:

```
# Resources for Preview, Spin-up, and Posterior simulations (these are run in series)
RunCores = 8
RunMem = 32000

# Resources for Prior + Jacobian simulations (these are run in parallel)
RunCoresJacobian = 1
RunMemJacobian = 4000
```

We may also want to introduce an option for the amount of cluster time to request (so long runs don't time out).

This may also apply to the `run_imi.sh` and `setup_imi.sh` driver scripts.

**Comment by laestrada** [comment]
Completed by #122
